### ISSUE TITLE
Singualrity support

### ISSUE THREAD

**Issue by mestia** [DomiStyle/docker-idrac6#23]
As singularity image under non-root users it fails with:
 `s6-mkdir: warning: unable to mkdir /var/run/s6: Read-only file system`

Would be great to make it work as a singularity image, as docker isn't really suitable for non-development machines due to it's security design.

**Comment by DomiStyle** [comment]
This won't work right now because the base image I use requires root permissions in order to set up the supervisor and a few other things. Are you sure this is any issue with Singularity? The same thing would happen if you were to force a non-root user on the container with Docker.

The Java application itself is run as whatever `USER_ID` and `GROUP_ID` is set to (default 1000:1000), so there is not much security risk associated with running the container as root.

**Comment by mestia** [comment]
I see now, the warning comes from s6. So most likely there are no issues with singularity.
