### ISSUE TITLE
The keycode hack doesn't seem to be working any more

### ISSUE THREAD

**Issue by rprihoda** [DomiStyle/docker-idrac6#28]
I launched a docker container. Booted server to BIOS boot menu but was unable to use the arrow keys to move the selection.

**Comment by SRJanel** [comment]
I have the same issue. Not all keys seem to be working.
On the PERC controller, most of the keys are not working (e.g. Arrows are not working, F1 key is working but F2 key is not working and so on). IDRAC_KEYCODE_HACK is enabled and "Pass all keystrokes to server" is selected.

**Comment by DomiStyle** [comment]
@rprihoda Did you enable/disable the keycode hack with environment variables?

@SRJanel Can you try one of the older versions?
https://hub.docker.com/r/domistyle/idrac6/tags

**Comment by rprihoda** [comment]
My bad. It seems to be working correctly with the environment variable set in the my docker-compose file.

**Comment by DomiStyle** [comment]
@rprihoda Good to hear.

@SRJanel Can you post your docker-compose/docker command?

**Comment by SRJanel** [comment]
Sorry for late reply.
`docker run -d -p 5800:5800 -p 5900:5900 -e IDRAC_HOST=192.168.3.19 -e IDRAC_USER=root -e IDRAC_PASSWORD=XXXX -e IDRAC_KEYCODE_HACK=true domistyle/idrac6`
Then I enable `Pass all keystrokes to server`.
I thought that there could be perhaps a problem because I was running the docker image inside a VM, but tried right now latest image directly on a windows host (and tested with firefox + Edge) but doesn't seem to be fully working.

Last time I thought it wasn't working only when I'm looking at the PERC controller interface. But I'm experiencing similar problems no matter what the iDRAC console is displaying. E.g. booted on my ESXi and things are actually quite random: the '-' key is pressed by itself at some points. Pressing Down arrow key seems to be actually pressing either '-' or Enter key (but not always), etc.. while some other keys like F2 for instance seems to be fully functioning.

Would you like me to grab any specific older version or go through all of them?

**Comment by DomiStyle** [comment]
@SRJanel No need to test older versions unless you know it worked previously, was only guessing because the title of the issue was "not working anymore".

Can you try a combination of disabling the keycode hack and checking/unchecking Pass all keystrokes to server? To disable the keycode hack make sure you remove `-e IDRAC_KEYCODE_HACK=true` completely instead of setting it to false.

**Comment by SRJanel** [comment]
Hmm.. :thinking: Seems to be working fine without the `IDRAC_KEYCODE_HACK` enabled.
But if I remember correctly, it wasn't working while I was on the PERC configuration utility.

I'll run some more tests in the next few days.

**Comment by SRJanel** [comment]
@DomiStyle 
Everything seems to be working correctly when:
1) I do not set the `IDRAC_KEYCODE_HACK` variable and
2) when I uncheck "Pass all keystrokes to server"

There's no issue for me. My bad.

**Comment by DomiStyle** [comment]
@SRJanel No worries, iDRAC 6 is a mess. Closing this then.
